name: lognito
description: Lognito, universal extendible logging library
version: 0.0.7
author: Vladimir Zahradnik
homepage: https://github.com/Code-Growers/lognito

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  http: 0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  cg_analysis:
    git:
      url: https://github.com/NomiAdam/cg_analysis.git
      ref: master

flutter:
